### ISSUE TITLE
'null' entry at bottom of 'Projects' page

### ISSUE THREAD

**Issue by pyxld-kris** [dev-launchers-sandbox/website#3]
An undesired 'null' entry shows at the bottom of the 'Projects' page

[
![f67500932cc0af8cedf8bd90c87883ab](https://user-images.githubusercontent.com/46331884/63965859-bb06ce00-ca5f-11e9-9968-72cc47f3ce2d.png)
](url)

After checking both the _dev-launchers_ and _dev-launchers-sandbox_ accounts, there doesn't seem to be a repo with the title 'null'. Most likely this is coming from an extra null entry in one of the github api responses, or the code parsing the api responses is inserting an extra entry at some point.

**Comment by dahuang37** [comment]
The null repo seem to be pulled from the github API. I also found the repo with the corresponding name: https://github.com/dev-launchers-sandbox/project__null

**Comment by pyxld-kris** [comment]
Ah, perfect. Thanks Daniel! Will delete that repo now
