### ISSUE TITLE
Project page - project links have incorrect endpoints

### ISSUE THREAD

**Issue by pyxld-kris** [dev-launchers-sandbox/website#5]
Currently, the project links on the 'Projects' page ("Open Dev" and "Open Prod" buttons) open Github links, but the desired behavior is to open up playable versions of the games held in these Github repos. 

We've used Travis CI to create a continuous integration/deployment system, along with Github pages and some clever routing in our backend, to allow playable games to be served up based on how specific path formats are used. This means that as students are working on their projects and committing to their repos, the games linked to in the 'Projects' page will be automatically updated and deployed. 

To access a playable, **development** version of a project repository the game can be accessed through: http://devlaunchers.com/dev/REPO_NAME_HERE

To access a playable, **production** version of a project repository the game can be accessed through: http://devlaunchers.com/launch/REPO_NAME_HERE

*Note: 
The only current working path is located at http://devlaunchers.com/dev/project__example-game but all project paths will be implemented shortly, and new projects set up using our Admin Tool will automatically create and configure all of this for us as projects are added

**Comment by dahuang37** [comment]
May I take this issue? :)

**Comment by pyxld-kris** [comment]
Yes of course, please do!

**Comment by dahuang37** [comment]
PR: https://github.com/dev-launchers-sandbox/website/pull/6

**Comment by dev-launchers-sandbox** [comment]
Great work, the site is looking so much better now
